[package]
name = "rust-print"
version = "0.1.0"
authors = ["César López-Natarén <cesar@nataren.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.11.0"
env_logger = "0.6.2"
log = "0.4.8"
